config/routes.rb
Rails.application.routes.draw do
  resources :trips
  
  root 'trips#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ApplicationRecord
  
  #This contains the time and position-data
  #It can be expanded to include additional information like speed
  
  #Most importantly, it can be sorted by position, time, and in ways other than by trip
  #This allows visibility of business peak-times and regional market-penetration  
  
  belongs_to :trip
  
  validates :timestamp, uniqueness: {scope: :trip_id}
end

app/models/trip.rb
class Trip < ApplicationRecord
  require 'csv'
  require 'open-uri'
  has_many :positions, dependent: :destroy  
  
  #validates :distance, presence: true
  #Validation is done through controller because multiple saves are required to get the distance
  #It's a bit ugly, but enables market-analysis (See below)
  
  def import_csv(csvfile)
    
    csv = CSV.parse(csvfile.read)
    #The test-files were semicolon-delimited, not really CSV. Adjusting for that.
    
    if (csv[0].length == 1) then csv = csv.collect{|i| i[0].split(";")} end
    
    #Strictly speaking, this could be handled by a serialized text-element, but
    #having the times and locations of rentals directly accessible can be very useful for market-analysis.
    #This is why the positions, the product-usage data, are kept in their own table
    
    csv.each do |row|
      self.positions.create(timestamp: Time.at(row[0].to_i), latitude: row[1].to_f, longitude: row[2].to_f)
    end
    
  end
  
  def get_google_data #Get total distance from Google Maps API    
    #arrange datapoints chonologically to build trip
    #doing this here rather than at input to allow for additional data available after oriignal upload
      datapoints = self.positions.sort{|a, b| a.timestamp.to_i <=> b.timestamp.to_i}
      
      #While it is usually preferable to make the minimum number of requests, Google charges by the matrix-element so
      #it is least expensive to retrieve 1x1 matrices containing only the desired distances
      
      #Build request parameters and set up request-loop
      #API documentation at https://developers.google.com/maps/documentation/distance-matrix/intro
      
      request_url = 'https://maps.googleapis.com/maps/api/distancematrix/json?'
      request_key = '&key=AIzaSyBe2zocWsImltBocK1xD2eEtKX-BYwH9gE' #This project's Google Maps JS API key
      distance = 0    
      
      datapoints.each_with_index do |destination, index|
        #It is computationally faster to use 'datapoints.length.times do', shift and datapoints[0], but this way
        #the array is preserved to allow other data to be calculated outside of the request-loop
        if index == 0 then next end
        
        origin = datapoints[index - 1]
        origin_string = '&origins=' + origin.latitude.to_s + ',' + origin.longitude.to_s
        destination_string = '&destinations=' + destination.latitude.to_s + ',' + destination.longitude.to_s      
        request_string = request_url + origin_string + destination_string + request_key
        
        response = open(request_string).read
        data = ActiveSupport::JSON.decode(response)
        distance += data['rows'][0]['elements'][0]['distance']['value'].to_f 
        
      end
      self.update_attribute(:distance, distance.to_f) #distance in m
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    redirect_to trips_path
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new#(trip_params)    

    respond_to do |format|
      if @trip.save && get_distance
        #The trip must be saved to create the position-records, so they are being added here
        
        format.html { redirect_to trips_path, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params) && get_distance
        #It is assumed that additionaly position-data is uploaded.
        #If not, then we should check whether that has happened before running get_distance as this involved Google API calls
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to @trip, notice: 'Trip was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.fetch(:trip, {})
    end
    
    def get_distance
      if params['trip'] && params['trip']['uploadfile'] then
        begin
          @trip.import_csv(params['trip']['uploadfile'])
          @trip.get_google_data
        #rescue
        #  @trip.errors[:base] << "File Format error."
        #  return false
        end
        return true
        #The trip must be re-saved with the distance
      elsif !@trip.distance        
        @trip.destroy
        @trip.errors[:base] << "Distance could not be calculated! Upload data-file."
        return false
        #but should not be kept if the distance could not be recorded
        #This would be done with a validation, but then the original saving, needed to get the positions associated properly, would fail
        
      else #It's an update not involving the distance
        #With nothing else being tracked yet, that means no changes were made, which is probably an error
        @trip.errors[:base] << "No changes made. Did you mean to do something?"
        return true
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveltracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= form_for(trip) do |f| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="upload_field">
  <%= f.label :Trip_File %> 
  <%= f.file_field(:uploadfile) %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :Upload_Data %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<!-- <%= link_to 'Show', @trip %> | -->
<%= link_to 'Trips', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Distance</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
      	<td><%= trip.distance %> Meters</td>
        <!-- ><td><%= link_to 'Show', trip %></td> Placeholder - May be used for Index of associated Positions to enable manual input / editing --> 
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Trips', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>